### ISSUE TITLE
How we can buy you a Coffee?

### ISSUE THREAD

**Issue by Shamoon78** [CloakedWayne/Monolith_Panels#1]

**Comment by CloakedWayne** [comment]
I'm glad you like my work! I added a link to my Ko-fi page.

**Comment by Shamoon78** [comment]
And how to find your KO-fi page?

**Comment by CloakedWayne** [comment]
The white icon is a link. I guess I'll have to make that more clear.

**Comment by Shamoon78** [comment]
Honestly, I have no Idea which white icon you are talking about. I am a bit
old school and not quick with web things .

**Comment by CloakedWayne** [comment]
Sorry, I'll make improvements.

[](https://ko-fi.com/cloakedwayne)

**Comment by Shamoon78** [comment]
I found it but this Ko-fi is only Paypal , I have no paypal and I donot
like it. What a shame.🥴
